### ISSUE TITLE
if ONLY ONE jira configuration  file  in conf dir the dashboard fails to load 

### ISSUE THREAD

**Issue by paulojaraujo** [goncalovalverde/seshat#15]
IndexError: list index out of range

Traceback (most recent call last)
File "/home/oluapojuara/projects/repos/seshat/viewer/dash.py", line 402, in display_page
            try:
                team = int(request.cookies["team_metrics_idx"])
            except BadRequestKeyError:
                team = 0
 
        title = f"{self.app.title} : {self.projects[team].name}"
 
        if pathname:
            logging.debug("Changing page to " + pathname)
        if pathname == "/lead_cycle_time":
            return self.show_hist_dash(team), title
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/oluapojuara/projects/repos/seshat/viewer/dash.py", line 402, in display_page
    title = f"{self.app.title} : {self.projects[team].name}"
IndexError: list index out of range

***************

If we put two files for two jira projects it works! and menu dashboard we have the selection available to select the project we want to analyze

**Comment by paulojaraujo** [comment]
If I clean the cookies the problem isn't anymore reproducible. 
How I notice the solution: I was using the address http://localhost:8050 that was throwing the error...But instead  launched 
 the address http://127.0.0.1:8050 problem wasn't reproducible anymore.
