### ISSUE TITLE
ttributeError: 'RangeIndex' object has no attribute '_with_freq'

### ISSUE THREAD

**Issue by paulojaraujo** [goncalovalverde/seshat#6]
oluapojuara@oluapojuara-Virtual-Machine:~/seshat-master$ ./seshat.py 
2020-12-22 13:25:14,903 - __main__ - INFO - <module> - Starting seshat. Let's do team magic!
2020-12-22 13:25:14,905 - root - ERROR - get_input - Reading input configuration from conf/Celfocus/celfocus_safaricom_jira_token.yml
2020-12-22 13:25:14,907 - root - DEBUG - <module> - Reading data for Jira Token Safaricom Chama
2020-12-22 13:25:14,908 - root - INFO - __init__ - Initializing Cache
2020-12-22 13:25:14,908 - root - DEBUG - get_data - Getting data from jira
2020-12-22 13:25:14,908 - root - DEBUG - get_data - Getting jira info cached 
2020-12-22 13:25:14,908 - root - DEBUG - read - Reading from cache /tmp/seshat_cache_cd33f585cc4f9a6ee753e168601fa763.pkl
2020-12-22 13:25:14,910 - root - DEBUG - lead_time - Calculating lead time for Created
2020-12-22 13:25:14,916 - root - DEBUG - cycle_time - Calculating cycle time for start:Created and end:To Do
2020-12-22 13:25:14,917 - root - DEBUG - cycle_time - Calculating cycle time for start:To Do and end:In Progress
2020-12-22 13:25:14,919 - root - DEBUG - cycle_time - Calculating cycle time for start:In Progress and end:Waiting for Response
2020-12-22 13:25:14,920 - root - DEBUG - cycle_time - Calculating cycle time for start:Waiting for Response and end:Approval
2020-12-22 13:25:14,921 - root - DEBUG - cycle_time - Calculating cycle time for start:Approval and end:Done
**Traceback (most recent call last):
  File "./seshat.py", line 26, in <module>
    team_metrics = viewer.team_metrics.Team_Metrics(cycle_data, source_config)
  File "/home/oluapojuara/seshat-master/viewer/team_metrics.py", line 22, in __init__
    self.throughput = calculator.flow.throughput(self.cycle_data, self.end_column)
  File "/home/oluapojuara/seshat-master/calculator/flow.py", line 32, in throughput
    throughput = calculator.tools.group_by_date(cycle_data, end_column)
  File "/home/oluapojuara/seshat-master/calculator/tools.py", line 15, in group_by_date
    df = df.resample("D", on=index).sum()
  File "/home/oluapojuara/.local/lib/python3.8/site-packages/pandas/core/resample.py", line 926, in f
    return self._downsample(_method, min_count=min_count)
  File "/home/oluapojuara/.local/lib/python3.8/site-packages/pandas/core/resample.py", line 1029, in _downsample
    obj.index = obj.index._with_freq(self.freq)
**AttributeError: 'RangeIndex' object has no attribute '_with_freq'****

oluapojuara@oluapojuara-Virtual-Machine:~/seshat-master$

**Comment by goncalovalverde** [comment]
Right now you need to put the same name in the configuration of the workflow in the left and in the right.
I know, it doesn't make much sense for now. This is thinking for a new version that will allow to map several status to the same workflow step
