### ISSUE TITLE
Throughput doesn't shows!

### ISSUE THREAD

**Issue by paulojaraujo** [goncalovalverde/seshat#9]
**My  team data doesn't use any sort of estimation...**

__output error bellow:__

![image](https://user-images.githubusercontent.com/70580625/102985988-fb694580-4507-11eb-81d8-393e9e9d342e.png)

*******************
KeyError: 'Done'

Traceback (most recent call last)
File "/home/oluapojuara/seshat-master/viewer/dash.py", line 413, in display_page
return self.show_throughput_dash(team), title
File "/home/oluapojuara/seshat-master/viewer/dash.py", line 179, in show_throughput_dash
    def show_throughput_dash(self, team=0):
        tm = self.projects[team]
        fig_throughput = tm.draw_throughput("all")
        # TODO: improve this logic
        if tm.has_story_points:
            fig_velocity = tm.draw_velocity("Total")
            fig_spoints_throughput = tm.draw_story_points()
        else:
            fig_velocity = {}
            fig_spoints_throughput = {}
 
File "/home/oluapojuara/seshat-master/viewer/team_metrics.py", line 74, in draw_velocity
velocity = calculator.flow.velocity(self.cycle_data).resample("W").sum()
File "/home/oluapojuara/seshat-master/calculator/flow.py", line 38, in velocity
table = pd.pivot_table(
File "/home/oluapojuara/.local/lib/python3.8/site-packages/pandas/core/reshape/pivot.py", line 111, in pivot_table
grouped = data.groupby(keys, observed=observed)
File "/home/oluapojuara/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 6515, in groupby
return DataFrameGroupBy(
File "/home/oluapojuara/.local/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 525, in __init__
        self.dropna = dropna
 
        if grouper is None:
            from pandas.core.groupby.grouper import get_grouper
 
            grouper, exclusions, obj = get_grouper(
                obj,
                keys,
                axis=axis,
                level=level,
                sort=sort,
File "/home/oluapojuara/.local/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 786, in get_grouper
raise KeyError(gpr)
KeyError: 'Done'
Traceback (most recent call last):
  File "/home/oluapojuara/seshat-master/viewer/dash.py", line 413, in display_page
    return self.show_throughput_dash(team), title
  File "/home/oluapojuara/seshat-master/viewer/dash.py", line 179, in show_throughput_dash
    fig_velocity = tm.draw_velocity("Total")
  File "/home/oluapojuara/seshat-master/viewer/team_metrics.py", line 74, in draw_velocity
    velocity = calculator.flow.velocity(self.cycle_data).resample("W").sum()
  File "/home/oluapojuara/seshat-master/calculator/flow.py", line 38, in velocity
    table = pd.pivot_table(
  File "/home/oluapojuara/.local/lib/python3.8/site-packages/pandas/core/reshape/pivot.py", line 111, in pivot_table
    grouped = data.groupby(keys, observed=observed)
  File "/home/oluapojuara/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 6515, in groupby
    return DataFrameGroupBy(
  File "/home/oluapojuara/.local/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 525, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/oluapojuara/.local/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 786, in get_grouper
    raise KeyError(gpr)
KeyError: 'Done

**Comment by goncalovalverde** [comment]
@paulojaraujo please pull the new version of the code. I forgot to remove an hard coded valued for the velocity hence triggering this problem. Should work now. Do a git pull in your side
